---
title: "Write Standardized Intermediate Sales Data to Sqlite"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output: 
    html_document:
        toc: true
        toc_float: true
        code_folding: show
---

**Notes**

**Guidelines**

A select set of variables should be included in the standardized database (see O365 > _Analyst Docs > Data Dictionary...xlsx).


```{r setup, message=FALSE}
library(tidyverse)
library(stringr)
library(lubridate)
knitr::opts_chunk$set(comment = NA)
```

## Load

```{r}
db_raw <- src_sqlite("../../../../../Data-sensitive/Data-Dashboards/__state__/raw-__period__.sqlite3")
src_tbls(db_raw)
```

```{r}
# tbl(db_raw, "sale") %>% glimpse()
sale <- tbl(db_raw, "sale") %>%
    select(raw_sale_id, cust_id = TXNL_CUST_ID, lic_id = TXNL_LICN_TYPE,
           year = TXNL_YEAR, source_year, dot = TXNL_TIMESTAMP, 
           start_date = TXNL_EFFECT_DATE, end_date = TXNL_EXPIRE_DATE,
           revenue = TXNL_STATE_COST) %>%
    collect()
glimpse(sale)
```

## Prep 

### License Year

```{r, fig.height=3}
summary(sale$year)
sale %>%
    count(year) %>%
    ggplot(aes(year, n)) +
    geom_col() +
    ggtitle("Sales by License Year")
```

### Transaction Date

```{r}
# select(sale, dot) %>% sample_n(5)
sale <- sale %>% mutate(
    dot_date = str_sub(dot, end = 10) %>% ymd(),
    dot_new = as.character(dot_date)
) 
sale %>%
    sample_n(5) %>%
    select(dot_new, dot)

# check missing
sale %>% filter(is.na(dot_new)) %>% nrow()
```

### Start Date

```{r}
# select(sale, start_date) %>% sample_n(5)
sale <- sale %>% mutate(
    start_date_date = mdy(start_date),
    start_date_new = as.character(start_date_date)
) 
sale %>%
    sample_n(5) %>%
    select(start_date_new, start_date)

# check missing
sale %>% filter(is.na(start_date_new)) %>% nrow()
```

### End Date

```{r}
# select(sale, end_date) %>% sample_n(5)
sale <- sale %>% mutate(
    end_date_date = mdy(end_date),
    end_date_new = as.character(end_date_date)
) 
sale %>%
    sample_n(5) %>%
    select(end_date_new, end_date)

# check missing
sale %>% filter(is.na(end_date_new)) %>% nrow()
```

#### Summarize Dates

```{r, fig.width=6}
x <- list()
x[[1]] <- count(sale, year = year(dot_date)) %>% mutate(timing = "transaction year")
x[[2]] <- count(sale, year = year(start_date_date)) %>% mutate(timing = "start year")
x[[3]] <- count(sale, year = year(end_date_date)) %>% mutate(timing = "end year")

bind_rows(x) %>%
    ggplot(aes(year, n)) +
    geom_col() +
    facet_wrap(~ timing, ncol = 1) +
    ggtitle("Sales by Year - Viewed with 3 different date metrics")
```

### Revenue

```{r}
summary(sale$revenue)
sale %>%
    ggplot(aes(revenue)) +
    geom_histogram() +
    scale_x_log10() +
    xlab("revenue (log10)") +
    ggtitle("Revenue Histogram")
```

## Finalize

- Renaming "new" columns and dropping old and unnecessary
- Adding a "source" column in case future data is appended

```{r}
sale <- sale %>% select(
    cust_id, lic_id, year, dot = dot_new, start_date = start_date_new,
    end_date = end_date_new, revenue, raw_sale_id
) %>%
    mutate(source_cust = as.integer("__period__"))
glimpse(sale)
```

## Write to Sqlite

```{r}
f <- "../../../../../Data-sensitive/Data-Dashboards/__state__/standard.sqlite3"
db_standard <- src_sqlite(f)
copy_to(db_standard, sale, temporary = FALSE)
```

```{r}
sessionInfo()
```
