---
title: "Pull address data for geocoding"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output: 
    html_document:
        toc: true
        toc_float: true
        code_folding: show
params:
    raw_db_file: "~/data/XX_Dashboard/raw.sqlite3"
    db_file: "~/data2/XX_Dashboard/lic.sqlite3"
    csv_file: 
---

START HERE - Rethinking what is needed here
1. pull addresses
2. write to standard (appending zipcode)

```{r setup, message=FALSE}
library(tidyverse)
library(tibble)
knitr::opts_chunk$set(comment = NA)
```

## Load

### Raw address data

- Table and column names will vary by state

```{r}
f <- "../../../../../Data-sensitive/Data-Dashboards/__state__/raw-__period__.sqlite3"
db_raw <- src_sqlite(f)
# src_tbls(db_raw)

cust_raw <- tbl(db_raw, "cust") %>% 
    select(cust_id = CustomerID, street = MailStreet1, city = MailCity, 
           state = MailState, zip = MailZip) %>% 
    collect(n = Inf)
glimpse(cust_raw)
```

### Cleaned data

- Only customers with state resident addresses are pulled, since the aim here is to identify county of residence

```{r}
db <- src_sqlite(params$db_file)
cust <- tbl(db, "cust") %>%
    filter(res == 1) %>%
    select(cust_id) %>%
    collect(n = Inf)
glimpse(cust)
```

## Prep

### Join address data

```{r}
cust_in <- cust
cust <- left_join(cust, cust_raw, by = "cust_id")
count(cust, state)
```

### Truncate Zips

- insure 5 digit length

```{r}
# count(cust_raw, nchar(zip))
count(cust, nchar(zip))

cust <- mutate(cust, zip = ifelse(nchar(zip) == 5, zip, NA))
count(cust, nchar(zip))
```

## Write to CSV

```{r}
"~/data/XX_Dashboard/geocode-addresses/cust-for-geocode.csv"
glimpse(cust)
dir.create(dirname(params$csv_file))
write.csv(cust, file = params$csv_file, row.names = FALSE)
```

```{r}
sessionInfo()
```

