---
title: "Load Raw Sales Data into sqlite database"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output: 
    html_document:
        toc: true
        toc_float: true
        code_folding: show
---

**Notes**


```{r setup, message=FALSE}
library(tidyverse)
library(salic)
knitr::opts_chunk$set(comment = NA)
```


## Load

```{r}
f <- "../../../../../Data-sensitive/Data-Dashboards/__state__/raw-__period__/"

# test
read_lines(f, n_max = 5)
read_csv(f, n_max = 5) %>% glimpse()
count_lines_textfile(f) # to ensure correct number of rows after data import
```


```{r}
read_csv(f, n_max = 5) %>% spec()
coltyp <- cols( )

sale <- read_csv(f, n_max = Inf, col_types = coltyp, progress = FALSE)
problems(sale)
glimpse(sale)
```


## Add Row IDs

```{r}
sale <- mutate(sale, raw_sale_id = row_number())
tail(sale$raw_sale_id)
```


## Write to sqlite

```{r}
f <- "../../../../../Data-sensitive/Data-Dashboards/__state__/raw-__period__.sqlite3"
db_raw <- src_sqlite(f)
copy_to(db_raw, sale, temporary = FALSE)
```

```{r}
sessionInfo()
```
